export const ACH_LIST_REQUEST = "ACH_LIST_REQUEST";
export const ACH_LIST_SUCCESS = "ACH_LIST_SUCCESS";
export const ACH_LIST_FAIL = "ACH_LIST_FAIL";

export const ACH_CREATE_REQUEST = "ACH_CREATE_REQUEST";
export const ACH_CREATE_SUCCESS = "ACH_CREATE_SUCCESS";
export const ACH_CREATE_FAIL = "ACH_CREATE_FAIL";

export const ACH_UPDATE_REQUEST = "ACH_UPDATE_REQUEST";
export const ACH_UPDATE_SUCCESS = "ACH_UPDATE_SUCCESS";
export const ACH_UPDATE_FAIL = "ACH_UPDATE_FAIL";

export const ACH_DELETE_REQUEST = "ACH_DELETE_REQUEST";
export const ACH_DELETE_SUCCESS = "ACH_DELETE_SUCCESS";
export const ACH_DELETE_FAIL = "ACH_DELETE_FAIL";
